### ISSUE TITLE
How to report security vulnerabilities?

### ISSUE THREAD

**Issue by mvondracek** [santomet/pv204_project#3]
Hello, our team is doing design and code review (https://github.com/mvondracek/PV204_smartcards_Emerald/issues/3) of your implementation in this repository as part of PV204 project.

As this project does not define [security policy](https://github.com/santomet/pv204_project/security/policy) how to securely report vulnerabilities, I would like to ask you what is a prefered way for it. For example, do you have a keybase account? Or should we just publicly share our reports as GitHub issues?

/cc @stepgenn @santomet @michalpavuk 

Thanks!

**Comment by michalpavuk** [comment]
Well, since this project is never intended to be used in production, I think that public GH issues are fine. However if you really want to I can send you a pubkey, but then I would need to forward everything to the team members and to Petr.

**Comment by mvondracek** [comment]
Alright, I agree, we will use just plaintext public issues.
